# Generated by Django 3.1.3 on 2020-11-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managewallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='refferd_user',
            field=models.CharField(default='asad', max_length=150),
            preserve_default=False,
        ),
    ]
