# Generated by Django 3.1.3 on 2020-11-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managewallet', '0002_customeuser_refferd_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
