# Generated by Django 3.1.3 on 2020-11-15 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managewallet', '0004_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managewallet.product')),
            ],
        ),
    ]
