# Generated by Django 3.1.3 on 2020-11-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managewallet', '0006_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
