# Generated by Django 3.1.3 on 2020-11-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managewallet', '0007_cart_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='buy_user',
            field=models.CharField(default='Ss', max_length=100),
            preserve_default=False,
        ),
    ]
